---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: tekton-pipelines-controller-vpa
  namespace: tekton-pipelines
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: tekton-pipelines-controller
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu","memory"]


---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: tekton-dashboard-vpa
  namespace: tekton-pipelines
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: tekton-dashboard
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu"]