---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chartmuseum
  namespace: chartmuseum
  annotations:
    fluxcd.io/automated: 'true'
spec:
  helmVersion: v3
  releaseName: chart-museum
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: chartmuseum
    version: 2.13.0
  rollback:
    enable: true
    retry: true
    maxRetries: 3
    timeout: 90
    force: true
    wait: true
  wait: true
  timeout: 90
  forceUpgrade: true

  values:
    image:
      repository: chartmuseum/chartmuseum
      tag: v0.12.0
      pullPolicy: IfNotPresent

    resources:
      requests:
        cpu: 64m
        memory: 64Mi
      limits:
        cpu: 96m
        memory: 96Mi

    replicaCount: 2
    persistence:
      enabled: false

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - name: charts.javiermatias.net
          path: /

    service:
      servicename:
      type: ClusterIP
      externalPort: 80

    deployment:
      annotations:
        reloader.stakater.com/auto: "true"

    serviceAccount:
      create: false
      name: eksctl-sa

    env:
      open:
        # storage backend, can be one of: local, alibaba, amazon, google, microsoft, oracle
        STORAGE: amazon
        # s3 bucket to store charts for amazon storage backend
        STORAGE_AMAZON_BUCKET: chartmuseum-backend
        # prefix to store charts for amazon storage backend
        STORAGE_AMAZON_PREFIX:
        # region of s3 bucket to store charts
        STORAGE_AMAZON_REGION: us-east-1
        # alternative s3 endpoint
        STORAGE_AMAZON_ENDPOINT:
        # server side encryption algorithm
        STORAGE_AMAZON_SSE:
        # gcs bucket to store charts for google storage backend
        # show debug messages
        DEBUG: true
        # output structured logs as json
        LOG_JSON: true
        # disable use of index-cache.yaml
        DISABLE_STATEFILES: false
        # disable Prometheus metrics
        DISABLE_METRICS: false
        # disable all routes prefixed with /api
        DISABLE_API: false
        # allow chart versions to be re-uploaded
        ALLOW_OVERWRITE: false
        # absolute url for .tgzs in index.yaml
        AUTH_ANONYMOUS_GET: false
        # sets the base context path
        # enable bearer auth
        BEARER_AUTH: false
        # auth realm used for bearer auth
        AUTH_REALM:
        # auth service used for bearer auth
        AUTH_SERVICE:
      field:
      # POD_IP: status.podIP
      secret:
        # username for basic http authentication
        BASIC_AUTH_USER:
        # password for basic http authentication
        BASIC_AUTH_PASS:
        # GCP service account json file
        GOOGLE_CREDENTIALS_JSON:
        # Redis requirepass server configuration
        CACHE_REDIS_PASSWORD:
      # Name of an existing secret to get the secret values ftom
      existingSecret: charts
      # Stores Enviromnt Variable to secret key name mappings
      existingSecretMappings:
        # username for basic http authentication
        BASIC_AUTH_USER: username
        # password for basic http authentication
        BASIC_AUTH_PASS: password
        # GCP service account json file
        GOOGLE_CREDENTIALS_JSON:
        # Redis requirepass server configuration
        CACHE_REDIS_PASSWORD:
