---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kibana
  labels:
    app: kibana
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kibana