apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: logstash-vpa
  namespace: monitoring
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: logstash-logstash
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu","memory"]
