apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: external-secrets-vpa
  namespace: external-secrets
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: external-secrets-kubernetes-external-secrets
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu","memory"]
