apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/chart-image: "semver:>=3.0"

  name: external-secrets
  namespace: external-secrets
spec:
  HelmVersion: v3
  releaseName: external-secrets
  chart:
    repository: https://godaddy.github.io/kubernetes-external-secrets/
    name: kubernetes-external-secrets
    version: 4.0.0

  wait: true
  timeout: 120
  rollback:
    timeout: 120
    enable: true

  values:
    resources:
      requests:
        cpu: 200m
        memory: 250Mi
      limits:
        cpu: 500m
        memory: 400Mi


    env:
      AWS_REGION: 'us-east-1'
      LOG_LEVEL: error
      POLLER_INTERVAL_MILLISECONDS: 300000
    securityContext:
      runAsNonRoot: false
      fsGroup: 65534

    serviceMonitor:
      enabled: true
      namespace: external-secrets

    replicaCount: 2

    image:
      repository: godaddy/kubernetes-external-secrets
      tag: 4.0.0
      pullPolicy: IfNotPresent


    serviceAccount:
      # Specifies whether a service account should be created
      create: false
      # Specifies annotations for this service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: eksctl-sa