---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: 'true'
spec:
  releaseName: metrics-server
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: metrics-server
    version: 2.11.1
  wait: true
  timeout: 120
  rollback:
    timeout: 120
    enable: true
  values:
    image:
      repository: k8s.gcr.io/metrics-server-amd64
      tag: v0.3.6
      pullPolicy: IfNotPresent

    extraVolumeMounts:
      - mountPath: /etc/tls-certs
        name: tls-certs
        readOnly: true

    extraVolumes:
      - name: tls-certs
        secret:
          defaultMode: 420
          secretName: vpa-tls-certs

    hostNetwork:
      enabled: true
    args:
      - --kubelet-preferred-address-types=InternalIP,InternalDNS