---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: unleash-replication
  namespace: unleash
secretDescriptor:
  backendType: secretsManager
  data:
    - key: unleash/postgres/replication/username/dev
      name: pg_repl_username
    - key: unleash/postgres/replication/password/dev
      name: pg_repl_password


---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: unleash-superuser
  namespace: unleash
secretDescriptor:
  backendType: secretsManager
  data:
    - key: unleash/postgres/superuser/username/dev
      name: pg_su_username
    - key: unleash/postgres/superuser/password/dev
      name: pg_su_password
