---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unleash
  namespace: unleash
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/chart-image: "semver: > 0.1"


spec:
  releaseName: unleash
  helmVersion: v3
  chart:
    repository: https://jmatias.github.io/unleash-deployment
    name: unleash
    version: 0.5.25
  timeout: 300
  wait: true
  rollback:
    timeout: 300
    enable: true
    retry: true
    wait: true
    maxRetries: 0
  values:
    image:
      repository: jmatiastw/unleash
      tag: 0.2.14
      imagePullPolicy: IfNotPresent

    serviceMonitor:
      enabled: false

    headerBackgroundColor: '#1e88e5'
    posgresqlExistingSecret:
      name: unleash-superuser
      usernameKey: pg_su_username
      passwordKey: pg_su_password

    resources:
      requests:
        cpu: 32m
        memory: 32Mi

      limits:
        cpu: 96m
        memory: 96Mi


    replicaCount: 3

    postgresql:
      database: unleash
      url: stolon-proxy.unleash

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      host: unleash.ekssandbox-tw.com
      path: /


    service:
      type: ClusterIP
      port: 80

